apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-node-app
  labels:
    app: my-node-app
spec:
  replicas: 3
  selector:
    matchLabels:
      app: my-node-app
  template:
    metadata:
      labels:
        app: my-node-app
    spec:
      containers:
      - name: my-node-app
        image: mik3asg/nodejs-k8s-demo:${IMAGE_TAG}  # Using an environment variable for the image tag
        ports:
        - containerPort: 3000
        env:
        - name: NODE_ENV
          value: "production"

