apiVersion: v1
kind: Service
metadata:
  name: my-node-app-service
  labels:
    app: my-node-app
spec:
  selector:
    app: my-node-app  # This should match the label in the deployment
  ports:
    - protocol: TCP
      port: 80  # External port exposed by the service
      targetPort: 3000  # Internal port on which the application is running inside the container
  type: LoadBalancer  # Exposes the service externally via a cloud provider's load balancer
